_BASE_: "base/Base-Panoptic-FPN.yaml"
MODEL:
  PIXEL_MEAN: [2.448, 0.765, 0.5355]
  PIXEL_STD: [9.435, 13.005, 11.373]
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MIN_SIZE_TEST: 400
  MAX_SIZE_TRAIN: 400
  MAX_SIZE_TEST: 400
  FORMAT: "RGB"
  MASK_FORMAT: bitmask
DATALOADER:
  NUM_WORKERS: 6
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
