_BASE_: "base/Base-Panoptic-FPN.yaml"
MODEL:
  PIXEL_MEAN: [18.71869,1.1018,0.73096]
  PIXEL_STD: [40.58461,15.3448,12.72729]
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MIN_SIZE_TEST: 400
  MAX_SIZE_TRAIN: 400
  MAX_SIZE_TEST: 400
  FORMAT: "RGB"
  MASK_FORMAT: bitmask
DATALOADER:
  NUM_WORKERS: 6
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
