_BASE_: "base/Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MIN_SIZE_TEST: 400
  MAX_SIZE_TRAIN: 400
  MAX_SIZE_TEST: 400
  FORMAT: "RGB"
  MASK_FORMAT: bitmask
DATALOADER:
  NUM_WORKERS: 6
MODEL:
  MASK_ON: True
  PIXEL_MEAN: [18.71869,1.1018,0.73096]
  PIXEL_STD: [40.58461,15.3448,12.72729]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 4096   # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 2  # only has two class (Optical Source, Radio Component)
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  BACKBONE:
    # Remove StopGrad at a specified stage so that no bottom layers are frozen
    # Default value is 2
    FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0,]]
    SIZES: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 44, 48, 56, 64, 70, 76, 80, 88, 96, 112, 120, 128, 136, 148, 164, 190, 214, 256, 1300, 1900]]
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (150000, 190000)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 50000
TEST:
  EVAL_PERIOD: 10000