_BASE_: "base/Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  MAX_SIZE_TRAIN: 200
  MAX_SIZE_TEST: 200
  FORMAT: "RGB"
DATALOADER:
  NUM_WORKERS: 6
MODEL:
  MASK_ON: False
  #WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  # Determine mean of our GBR channels
  #Layer 0 Mean: [16.04951283] Std: [30.84018818]
  #Layer 1 Mean: [2.39659263] Std: [13.68579664]
  #Layer 2 Mean: [1.61892633] Std: [11.35677329]
  PIXEL_MEAN: [15.905, 2.394, 1.611]
  PIXEL_STD: [30.759, 13.674, 11.303]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 2048   # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 1  # only has one class (Optical Source)
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  BACKBONE:
    # Remove StopGrad at a specified stage so that no bottom layers are frozen
    # Default value is 2
    FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0,]]
    SIZES: [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,32]]
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (210000, 250000)
  MAX_ITER: 60000
