_BASE_: "source_fast_base_all_fixed.yaml"
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 8
  STEPS: (100000, 190000)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 25000
TEST:
  EVAL_PERIOD: 0
  EXTRA_EVAL: []