_BASE_: "source_base.yaml"
MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # Determine mean of our GBR channels
  PIXEL_MEAN: [2.851, 1.849, 1.306, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
  PIXEL_STD: [7.125, 16.117, 14.239 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0]
