_BASE_: "base/Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MIN_SIZE_TEST: 400
  MAX_SIZE_TRAIN: 400
  MAX_SIZE_TEST: 400
  FORMAT: "RGB"
  MASK_FORMAT: bitmask
MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  LOAD_PROPOSALS: True
  PIXEL_MEAN: [18.71869,1.1018,0.73096]
  PIXEL_STD: [40.58461,15.3448,12.72729]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 4096
    NUM_CLASSES: 1  # only has one class (Optical Source)
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0,]]
    ANGLES: [[0.,]]
    SIZES: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 44, 48, 56, 64, 70, 76, 80, 88, 96, 112, 120, 128, 136, 148, 164, 190, 214, 256, 1300, 1900]]
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 50000
TEST:
  EVAL_PERIOD: 200