_BASE_: "/home/s2153246/lofarnn/detectron2/configs/Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  MAX_SIZE_TRAIN: 200
  MAX_SIZE_TEST: 200
  FORMAT: "RGB"
MODEL:
  MASK_ON: False
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # Determine mean of our GBR channels
  PIXEL_MEAN: [0.402, 0.158, 0.120]
  PIXEL_STD: [6.377, 2.393, 1.534]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  BACKBONE:
    # Remove StopGrad at a specified stage so that no bottom layers are frozen
    # Default value is 2
    FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0,]]
    SIZES: [[1, 4, 9, 16, 25, 32, 36, 49, 64, 128]]
SOLVER:
  BASE_LR: 0.0003
  STEPS: (210000, 250000)
  MAX_ITER: 270000
