_BASE_: "Base-TridentNet-Fast-C4.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/trident_test1/" 
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  # Determine mean of our GBR channels
  PIXEL_MEAN: [242.868, 246.401, 246.283]
  PIXEL_STD: [52.314, 15.5175, 44.389]
  BACKBONE:
    # Remove StopGrad at a specified stage so that no bottom layers are frozen
    # Default value is 2
    FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.333, 0.5, 1.0, 2.0, 3.0]]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  BASE_LR: 0.02
INPUT:
  SCALE_FACTOR: 1.5151515151515151 #1.0 #4.545454545454546
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  MAX_SIZE_TRAIN: 200
  MAX_SIZE_TEST: 200
  #SCALE_FACTOR: 4.545454545454546
DATASETS:
  OUTPUT_DIR: "/data/mostertrij/tridentnet/output/trident_test1/" 
  IMAGE_DIR: "/data/mostertrij/data/frcnn_images/"
  COMP_CAT_PATH: '/data/mostertrij/data/catalogues/LOFAR_HBA_T1_DR1_merge_ID_v1.2.comp.fits'
  FITS_PATH: "/data/mostertrij/data/frcnn_images/cutouts/"
